config/routes.rb
Rails.application.routes.draw do


  #generates /concerts/get_events route
  resources :events do
    get :get_events, on: :collection
    # GET /apartments/:apartment_id/map_locations
    get 'map_location'
  end



  resources :books

  resources :concerts

  devise_for :users


  root 'welcome#index'

  get 'welcome/index'

  get 'welcome/calendar'

  get 'welcome/about'

  get 'welcome/search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

    @concerts = Concert.order 'created_at DESC'
    @books = Book.order 'created_at DESC'

  end

  def show

  end

  def search

    if !params[:search_params].nil? && !params[:search_params].to_s.strip.empty?
      @concert_results = Concert.search(params[:search_params])
      @book_results = Book.search(params[:search_params])
      @event_results = Event.search(params[:search_params])
      @search_results = @concert_results + @book_results + @event_results
    elsif params[:search_params].nil? || params[:search_params].to_s.strip.empty?
      redirect_back(fallback_location: root_path) and return flash[:alert] = "You must type something in the search bar."
    end

    if @search_results.nil? || @search_results.empty?
      redirect_back(fallback_location: root_path)
      flash[:alert] = "Sorry! There were no results matching your search."
    end
  end


  def about

  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="flash-alert">
    <% if flash[:alert] %>
    <%= flash[:alert] %>
    <% end %>
  </div>
    <div class="thumbnail text-center">
        <img src="/sarah.png" alt="" class="img-responsive">
        <div class="caption">
            <h1><strong>Sarah Burnand</strong></h1>
        </div>
    </div>
</div>

<div class="row">
    <p><strong>Sarah Smile</strong></p>
    <br>
    <p>My mother named me after a Hall & Oats song.</p>
    <br>
    <p>I was about 5 or 6 years old when it happened. During this time, in the mid 90s, ‘Nsync and Spice Girls were at the top of their game. Giant billboards lined the streets promoting these big time pop acts. Well, yes I did listen to these overtly advertised personas but I never felt the spark of what music could really do for me. It was at this young age, I was spying on my older sister and her best friend as they listened to music and talked about the boys in their class, that this sound hit me. I started to hear these heavy guitars and lead vocals that made me immediately give up my hiding place behind the door. They let me in and we all sat and listened to No Doubt’s “Tragic Kingdom”. Two weeks later, with a smile on my face, I took the money from allowance and as many odd jobs around the house my mom would allow me to do, and walked my happy little ass into that Warehouse down the street. That’s when I bought the first two albums that would shape me as a young girl. Along with “Tragic Kingdom”, I also purchased Garbage’s “Version 2.0”. The power of these female rockers filled my ears for the years to follow.</p>
    <p>That was until at about 12, when my mom (coolest woman in the world) took me to my first concert. The lineup was amazing for a young female rocker like myself, The Distillers then Garbage then No Doubt. All women, who took this genre in their hands and made it their own. These women had become my best friends through their albums over the years and seeing them live lit a fire in me.</p>
    <p>If I could say one thing to Gwen Stefani it would be “Hey, so I know I’m a super nerd. But, thank you for being my best friend when I felt alone. Thank you for always evolving your writing. In those times, you helped me grow too. Also, this one time in Mexico my best friend ran into you and said ‘hey my best friend, Sarah Burnand is your biggest fan’, and I still hold onto that. #thankyoukendahl</p>
    <p>This fire led to my discovery of other incredible women in music such as Kathleen Hanna  of Bikini Kill. This woman has her own holiday in Portland. She created a generation. What else was I living to do? It was the first time I saw feminism and music set in motion. With the combination of all of these incredible women in my life,I would not be silenced. I would not be demeaned. Music took whatever it wanted from me. Yet, I took more from it. From that first concert, I was hooked. It was a stronger high than any drug I could find. So, here I am still craving more.</p>
</div>
<br>
<br>
    <div class="row">
      <table>
				<tr>
          <div class="col-lg-6">
            <h2 style="padding-left: 6%;">
            <span class="glyphicon glyphicon-envelope"></span> <a href="mailto:burnandtunes@gmail.com"  target="_blank">burnandtunes@gmail.com</a>
          </h2>
        </div>
        <div class="col-lg-6">
            <h2 style="padding-left: 20%;">
              <span class="glyphicon glyphicon-phone"></span> Cell<a href="tel:8586995303"> +1(858) 699-5305
              </h2>
          </div>
				</tr>
		</table>
  </div>
    </div>

app/views/welcome/calendar.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="flash-alert">
    <% if flash[:alert] %>
    <%= flash[:alert] %>
    <% end %>
  </div>
  <div class="col-lg-12">
    <div id="calendar" class="tab-pane fade in active"></div>
  </div>
</div>


<% if current_user %>
  <div class="row">
    <div class="col-md-3">
      <%= button_to 'Add New Event', new_event_path, :method => "get", :class => "btn btn-warning", :style => "margin-top: 25px; font-size: 18px; width: 60%; height: 50px;"%>
    </div>
    <div class="col-md-3">
      <%= button_to 'View All Events', events_path, :method => "get", :class => "btn btn-info", :style => "margin-top: 25px; font-size: 18px; width: 60%; height: 50px;"%>
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>


  <div class="row">
    <div class="flash-alert">
      <% if flash[:alert] %>
      <%= flash[:alert] %>
      <% end %>
    </div>

    <header class="intro-header" style="background-image: url(/lf.jpg)">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1 class="cinzel"><strong>What's New</strong></h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div id="live_feed">

      <div class="col-lg-6">
        <h1 class="cinzel">Concerts</h1>
        <% @concerts.limit(4).each do |concert| %>
          <table>
            <tr>
              <td>
                <a href="/concerts/<%= concert.id %>">
                  <hr>
                  <%= image_tag concert.image.url(:large), :class => "concert_image", :style => "float: left; margin-right: 12px; max-height: 70%; min-width: 25%;" %>
                <h2 class="cinzel"><strong><%= concert.title %></strong></h2>
                <h4>
                  <% if concert.review.length > 165 %>
                    <%= truncate(concert.review, length: 165) %>
                    <%= link_to '...Read more', concert_path(concert), class: "read-more-#{concert.id}" %>
                  <% else %>
                    <%= concert.review %>
                  <% end %>
                </h4>
              </a></td>
            </tr>
          </table>
      <% end %>
    </div>

    <div class="col-lg-6">
      <h1 class="cinzel">Books</h1>
      <% @books.limit(4).each do |book| %>
        <table>
          <tr>
            <td>
              <a href="/books/<%= book.id %>">
                <hr>
                <%= image_tag book.image.url(:large), :class => "book_image", :style => "float: left; margin-right: 12px; margin-bottom: 5px; max-height: 65%; min-width: 25%;" %>
              <h2 class="cinzel"></strong><%= book.title %></strong></h2>
              <h4>
                <% if book.review.length > 165 %>
                  <%= truncate(book.review, length: 165) %>
                  <%= link_to '...Read more', book_path(book), class: "read-more-#{book.id}" %>
                <% else %>
                  <%= book.review %>
                <% end %>
              </h4>
            </a></td>
          </tr>
        </table>
    <% end %>
    </div>

  </div>

</div>

app/views/welcome/search.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="flash-alert">
    <% if flash[:alert] %>
    <%= flash[:alert] %>
    <% end %>
  </div>
    <header class="intro-header" style="background-image: url(/concerts.png)">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1 class="cinzel"><strong>Search Results</strong></h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div id="live_feed">
      <% if @concert_results.length > 0 %>
        <div class="col-lg-6">
          <h2 class="cinzel"><em>Concert Reviews</em></h2>
          <% @concert_results.each do |concert| %>
            <table>
              <tr>
                <td>
                  <a href="/concerts/<%= concert.id %>">
                    <hr>
                    <%= image_tag concert.image.url(:large), :class => "concert_image", :style => "float: left; margin-right: 12px; max-height: 70%; min-width: 25%;" %>
                  <h2 class="cinzel"><strong><%= concert.title %></strong></h2>
                  <h4>
                    <% if concert.review.length > 165 %>
                      <%= truncate(concert.review, length: 165) %>
                      <%= link_to '...Read more', concert_path(concert), class: "read-more-#{concert.id}" %>
                    <% else %>
                      <%= concert.review %>
                    <% end %>
                  </h4>
                </a></td>
              </tr>
            </table>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <% if @book_results.length > 0 %>
      <div class="col-lg-6">
        <h2 class="cinzel"><em>Book Reviews</em></h2>
        <% @book_results.each do |book| %>
          <table>
            <tr>
              <td>
                <a href="/books/<%= book.id %>">
                  <hr>
                  <%= image_tag book.image.url(:large), :class => "concert_image", :style => "float: left; margin-right: 12px; max-height: 70%; min-width: 25%;" %>
                <h2 class="cinzel"><strong><%= book.title %></strong></h2>
                <h4>
                  <% if book.review.length > 165 %>
                    <%= truncate(book.review, length: 165) %>
                    <%= link_to '...Read more', book_path(book), class: "read-more-#{book.id}" %>
                  <% else %>
                    <%= book.review %>
                  <% end %>
                </h4>
              </a></td>
            </tr>
          </table>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <% if @event_results.length > 0 %>
      <div class="col-lg-6">
        <h2 class="cinzel"><em>Events</em></h2>
        <% @event_results.each do |event| %>
          <table>
            <tr>
              <td>
                <a href="/events/<%= event.id %>">
                  <hr>
                <h2 class="cinzel"><strong><%= event.title %></strong></h2>
                <h4>
                  <% if event.description.length > 165 %>
                    <%= truncate(event.description, length: 165) %>
                    <%= link_to '...Read more', event_path(event), class: "read-more-#{event.id}" %>
                  <% else %>
                    <%= event.description %>
                  <% end %>
                </h4>
                <h4>
                    <%= event.date %>
                </h4>
              </a></td>
            </tr>
          </table>
        <% end %>
      </div>
    <% end %>
  </div>


</div>