config/routes.rb
Rails.application.routes.draw do


  #generates /concerts/get_events route
  resources :events do
    get :get_events, on: :collection
    # GET /apartments/:apartment_id/map_locations
    get 'map_location'
  end



  resources :books

  resources :concerts

  devise_for :users


  root 'welcome#index'

  get 'welcome/index'

  get 'welcome/calendar'

  get 'welcome/about'

  get 'welcome/search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/concert.rb
class Concert < ApplicationRecord
  
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment :image, presence: true,
    content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
    size: { in: 0..10.megabytes }
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all.order 'created_at DESC'
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    if current_user
      @concert = Concert.new
    end
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to '/concerts', notice: 'Concert was successfully created.' }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: 'Concert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_params
      params.require(:concert).permit(:title, :review, :image, :url)
    end
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/concerts/_form.html.erb
<%= form_for((concert), html: { multipart: true })  do |f| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table id="new_review">
      <tbody>
        <div class="col-md-4">
        <tr>
          <td><%= f.label :title %></td>
          <td><%= f.text_field :title, :style => "height: 35px; color: black; width: 400px; margin-bottom: 20px; margin-top: 20px; margin-left: -120px;" %></td>
        </tr>
        <tr>
          <td><%= f.label :review %></td>
          <td><%= f.text_area :review, :style => "height: 200px; width: 400px; color: black; margin-left: -120px;" %></td>
        </tr>
        <tr>
          <td><%= f.label :image%></td>
          <td><%= f.file_field :image, :style => "margin-left: -120px;"%></td>
        </tr>
        <tr>
          <td><%= f.label :url%></td>
          <td><%= f.text_area :url, :style => "height: 35px; color: black; width: 400px; margin-bottom: 20px; margin-top: 20px; margin-left: -120px;" %></td>
        </tr>
        <tr>
          <td> <%= f.submit class: "btn btn-primary", :style => "width: 125px; font-size: 17px; margin-top: 10px; padding-left: -10px;" %> <%= button_to 'Back', concerts_path, :class => "btn btn-success", :method => "get", :style => "width: 120px; font-size: 17px; margin-top: 10px;" %></td>
        </tr>
      </tbody>
</table>


<% end %>

app/views/concerts/edit.html.erb
<div class="flash-alert">
  <% if flash[:alert] %>
  <%= flash[:alert] %>
  <% end %>
</div>
<h1>Editing Concert</h1>


<%= render 'form', concert: @concert %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>
<!-- outermost row -->
<div class="row">
  <div class="flash-alert">
    <% if flash[:alert] %>
    <%= flash[:alert] %>
    <% end %>
  </div>
  <!-- image row -->
  <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url(concerts.png)">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1 class="cinzel"><strong>Concert Reviews</strong></h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

  <!-- concert reviews row -->
  <div id="live_feed">

    <div class="row">
      <div class="col-md-10">
      <% @concerts.each do |concert| %>
      <table align="center">
        <tr>
          <td>
            <hr>
            <a href='/concerts/<%= concert.id %>'>
            <div class="col-lg-3">
              <%= image_tag concert.image.url(:large), :class => "concert_image"  %>
            </div>



        <div class="col-lg-9">
                  <h2 class="cinzel"><strong><%= concert.title %></strong></h2>
                  <h4>
                    <% if concert.review.length > 200 %>
                      <%= truncate(concert.review, length: 200) %>
                      <%= link_to '...Read more', concert_path(concert), class: "read-more-#{concert.id}" %>
                    <% else %>
                      <%= concert.review %>
                    <% end %>
                  </h4>
                    <% if concert.url.present? %>
                      <h4><a href="<%=concert.url%>" class="url">Check Out This Link</a></h4>
                    <% end %>
                </a></td>
              </tr>
            </table>
        <% end %>
      </div>
    </div>
  </div>

</div>
<div class="row">
  <div class="col-lg-3">
    <% if current_user %>
      <%= link_to 'New Concert Review', new_concert_path, :class => "btn btn-info", :style => "margin-top: 15px;" %>
    <% end %>
</div>
  </div>

<!-- closing outermost row -->
</div>

app/views/concerts/new.html.erb
<div class="flash-alert">
  <% if flash[:alert] %>
  <%= flash[:alert] %>
  <% end %>
</div>
<h1>New Concert</h1>

<%= render 'form', concert: @concert %>

app/views/concerts/show.html.erb
<!-- Page Header -->
  <!-- Set your background image for this header on the line below. -->
  <div class="flash-alert">
    <% if flash[:alert] %>
    <%= flash[:alert] %>
    <% end %>
  </div>
  <header class="intro-header" style="background-image: url(<%= @concert.image.url %>)">
      <div class="container">
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                  <div class="post-heading">
                      <h1 class="cinzel"><%= @concert.title %></h1>
                  </div>
              </div>
          </div>
      </div>
  </header>

  <!-- Post Content -->
  <article>
      <div class="container">
          <div class="row">
              <div class="col-lg-10" style="margin-left: 6%; ">
                  <p class="review"><%= @concert.review %></p>
                  <% if @concert.url.present? %>
                    <p><a href="<%=@concert.url%>" class="review url">URL: <%= @concert.url.to_s %></a></p>
                  <% end %>
                  <br>
                  <div class="row">
                    <% if user_signed_in? %>
                      <div class="col-xs-1">
                        <%= button_to 'Edit', edit_concert_path(@concert), :class => "btn btn-warning", :method => :get %>
                      </div>
                      <div class="col-xs-2">
                      <%= link_to 'Destroy', concert_path, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                      </div>
                    <% end %>
                    <div class="col-xs-1">
                        <%= button_to 'Back', request.referer, :class => "btn btn-primary", :method => :get  %>
                    </div>
                    <div class="col-sm-10"> <p></p></div>
              </div>
          </div>
      </div>
  </article>


  <!-- jQuery -->
  <script src="vendor/jquery/jquery.min.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

  <!-- Contact Form JavaScript -->
  <script src="js/jqBootstrapValidation.js"></script>
  <script src="js/contact_me.js"></script>

  <!-- Theme JavaScript -->
  <script src="js/clean-blog.min.js"></script>