config/routes.rb
Rails.application.routes.draw do


  #generates /concerts/get_events route
  resources :events do
    get :get_events, on: :collection
    # GET /apartments/:apartment_id/map_locations
    get 'map_location'
  end



  resources :books

  resources :concerts

  devise_for :users


  root 'welcome#index'

  get 'welcome/index'

  get 'welcome/calendar'

  get 'welcome/about'

  get 'welcome/search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
validates_attachment :image, presence: true,
    content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
    size: { in: 0..10.megabytes }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all.order 'created_at DESC'
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to "/books", notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :review, :image, :url)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for((book), html: { multipart: true }) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table id="new_review">
        <tbody>
          <div class="col-md-4">
          <tr>
            <td><%= f.label :title %></td>
            <td><%= f.text_field :title, :style => "height: 35px; color: black; width: 400px; margin-bottom: 20px; margin-top: 20px; margin-left: -120px;" %></td>
          </tr>
          <tr>
            <td><%= f.label :review %></td>
            <td><%= f.text_area :review, :style => "height: 200px; width: 400px; color: black; margin-left: -120px;" %></td>
          </tr>
          <tr>
            <td><%= f.label :image%></td>
            <td><%= f.file_field :image, :style => "margin-left: -120px;"%></td>
          </tr>
          <tr>
            <td><%= f.label :url%></td>
            <td><%= f.text_area :url, :style => "height: 35px; color: black; width: 400px; margin-bottom: 20px; margin-top: 20px; margin-left: -120px;"%></td>
          </tr>
          <tr>
            <td> <%= f.submit class: "btn btn-primary", :style => "width: 120px; font-size: 17px; margin-top: 10px" %> <%= button_to 'Back', concerts_path, :class => "btn btn-success", :method => "get", :style => "width: 120px; font-size: 17px; margin-top: 10px;" %></td>
          </tr>
        </tbody>
  </table>


  <% end %>

app/views/books/edit.html.erb
<div class="flash-alert">
  <% if flash[:alert] %>
  <%= flash[:alert] %>
  <% end %>
</div>

<h1>Editing Book</h1>

<%= render 'form', book: @book %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<!-- outermost row -->
<div class="row">
  <div class="flash-alert">
    <% if flash[:alert] %>
    <%= flash[:alert] %>
    <% end %>
  </div>
  <!-- image row -->
  <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url(book_reviews.png)">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1 class="cinzel"><strong>Book Reviews</strong></h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

  <!-- book reviews row -->
  <div id="live_feed">

    <div class="row">
      <div class="col-md-10">
      <% @books.each do |book| %>
      <table align="center">
        <tr>
          <td>
            <hr>
            <a href='/books/<%= book.id %>'>
            <div class="col-lg-3">
              <%= image_tag book.image.url(:large), :class => "concert_image"  %>
            </div>



        <div class="col-lg-9">
                  <h2 class="cinzel"><strong><%= book.title %></strong></h2>
                  <h4>
                    <% if book.review.length > 200 %>
                      <%= truncate(book.review, length: 200) %>
                      <%= link_to '...Read more', book_path(book), class: "read-more-#{book.id}" %>
                    <% else %>
                      <%= book.review %>
                    <% end %>
                  </h4>
                  <% if book.url.present? %>
                    <h4><a href="<%=book.url%>" class="url">Check Out This Link</a></h4>
                  <% end %>
                </a></td>
              </tr>
            </table>
        <% end %>
      </div>
    </div>
  </div>


  </div>
  <div class="row">
    <div class="col-lg-3">
      <% if current_user %>
        <%= link_to 'New Book Review', new_book_path, :class => "btn btn-info", :style => "margin-top: 15px;" %>
      <% end %>
  </div>
</div>

<!-- closing outermost row -->
</div>

app/views/books/new.html.erb
<div class="flash-alert">
  <% if flash[:alert] %>
  <%= flash[:alert] %>
  <% end %>
</div>
<h1>New Book</h1>

<%= render 'form', book: @book %>

app/views/books/show.html.erb
<!-- Page Header -->
  <!-- Set your background image for this header on the line below. -->
  <div class="flash-alert">
    <% if flash[:alert] %>
    <%= flash[:alert] %>
    <% end %>
  </div>
  <header class="intro-header" style="background-image: url(<%= @book.image.url %>)">
      <div class="container">
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                  <div class="post-heading">
                      <h1 class="cinzel"><%= @book.title %></h1>
                      <h3 style="text-align: center;"><em><%= @book.created_at.to_s%></em></h3>
                  </div>
              </div>
          </div>
      </div>
  </header>

  <!-- Post Content -->
  <article>
      <div class="container">
          <div class="row">
            <div class="col-lg-10" style="margin-left: 6%;">
                  <p class="review">
                    <%= @book.review %>
                  </p>
                  <% if @book.url.present? %>
                    <p><a href="<%=@book.url%>" class="review url">URL: <%= @event.url.to_s %></a></p>
                  <% end %>
                  <br>
                  <div class="row">
                    <% if user_signed_in? %>
                      <div class="col-xs-1">
                        <%= button_to 'Edit', edit_book_path(@book), :class => "btn btn-warning", :method => :get %>
                      </div>
                      <div class="col-xs-2">
                      <%= link_to 'Destroy', book_path, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                      </div>
                    <% end %>
                    <div class="col-xs-1">
                      <%= button_to 'Back', request.referer, :class => "btn btn-primary", :method => :get  %>
                    <div>
                      <div class="col-sm-10"> <p></p></div>
              </div>
          </div>
      </div>
  </article>


  <!-- jQuery -->
  <script src="vendor/jquery/jquery.min.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

  <!-- Contact Form JavaScript -->
  <script src="js/jqBootstrapValidation.js"></script>
  <script src="js/contact_me.js"></script>

  <!-- Theme JavaScript -->
  <script src="js/clean-blog.min.js"></script>